"""Self-contained Explore page served by FastAPI."""

from .theme import theme_head
from .ui_common import sidebar_html, PROVIDER_ICONS_JS, MEDIA_CARD_CSS, MEDIA_CARD_JS, PROVIDER_NAV_CSS


def explore_html() -> str:
    return r'''<!doctype html><html lang="zh-CN"><head>''' + theme_head() + r'''<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>汇影 · 影视发现</title><style>
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 78% 5%,var(--accent-soft),var(--bg-deep) 42%);color:var(--text);font:14px system-ui,"Microsoft YaHei"}.shell{display:grid;grid-template-columns:240px minmax(0,1fr);min-height:100vh}.side{position:sticky;top:0;height:100vh;padding:20px 14px;background:var(--sidebar-bg);border-right:1px solid var(--sidebar-border)}.logo{font-size:23px;font-weight:800;color:var(--accent-primary);padding:5px 8px 27px}.group{font-size:12px;color:var(--text-muted);border-bottom:1px solid var(--border-secondary);padding:18px 8px 8px}.nav{display:block;color:var(--text-secondary);text-decoration:none;padding:13px 12px;margin:6px 0;border-radius:11px;font-weight:700}.nav:hover,.nav.active{color:var(--accent-primary);background:var(--hover-bg)}.page{min-width:0}.top{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:4px;padding:10px 22px;background:var(--bg-secondary);border-bottom:1px solid var(--border-primary);overflow:auto}.brand{font-size:24px;font-weight:800;color:var(--accent-primary);margin-right:18px}''' + PROVIDER_NAV_CSS + '''.wrap{max-width:1700px;margin:auto;padding:20px 28px 50px}.filters{background:var(--panel);padding:14px 18px;border:1px solid var(--border-primary);border-radius:14px}.row{display:flex;gap:12px;margin:9px 0;align-items:flex-start}.label{width:52px;color:var(--muted);padding-top:7px;flex:none}.chips{display:flex;flex-wrap:wrap;gap:6px}.chip{border:1px solid transparent;background:var(--chip-bg);color:var(--chip-text);padding:7px 12px;border-radius:18px;cursor:pointer}.chip:hover{border-color:var(--chip-hover);color:var(--accent-primary)}.chip.active{background:var(--accent-soft);color:var(--accent-primary);border-color:var(--accent-primary)}.status{display:flex;justify-content:space-between;align-items:center;margin:15px 2px;color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(132px,1fr));gap:13px}''' + MEDIA_CARD_CSS + '''.state{padding:55px 20px;text-align:center;background:var(--state-bg);border:1px solid var(--state-line);border-radius:14px}.state button{margin:6px;padding:9px 14px;border:1px solid var(--accent-primary);background:var(--button-secondary-bg);color:var(--accent-primary);border-radius:8px;cursor:pointer}.skeleton{height:290px;border-radius:11px;background:linear-gradient(90deg,var(--skeleton-a) 25%,var(--skeleton-b) 37%,var(--skeleton-a) 63%);background-size:400% 100%;animation:s 1.2s infinite}@keyframes s{to{background-position:-100% 0}}.sentinel{text-align:center;padding:22px;color:var(--text-muted)}.hidden{display:none}@media(max-width:850px){.shell{display:block}.side{display:none}.wrap{padding:12px}.row{display:block}.label{width:auto;margin-bottom:5px}.grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}}@media(max-width:430px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style></head><body><div class="shell">''' + sidebar_html("explore") + '''<section class="page"><header class="top"><div class="brand">🌍 汇影</div><div id="providers"></div></header><main class="wrap"><section class="filters" id="filters"></section><div class="status"><span id="summary">准备加载</span><button class="chip" id="reset">重置筛选</button></div><section id="content"></section><div id="sentinel" class="sentinel hidden">继续向下滚动加载</div></main></section></div><script>
const S={provider:'douban',media_type:'movie',sort:'recommend',genre:'',country:'',region:'',language:'',year:'',rating:0,page:1,loading:false,has_more:false,request:0};let META={genres:[],countries:[],sorts:[],years:[]},tmdbGenres=[],controller=null;const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function chip(label,key,value){return `<button class="chip ${String(S[key])===String(value)?'active':''}" data-key="${key}" data-value="${esc(value)}">${esc(label)}</button>`}function row(label,html){return `<div class="row"><div class="label">${label}</div><div class="chips">${html}</div></div>`}
function drawFilters(){let html=row('类型',chip('电影','media_type','movie')+chip('电视剧','media_type','tv'));if(S.provider==='douban'){html+=row('排序',META.sorts.map(x=>chip(x.name,'sort',x.code)).join(''))+row('风格',chip('全部','genre','')+META.genres.map(x=>chip(x,'genre',x)).join(''))+row('地区',chip('全部','country','')+META.countries.map(x=>chip(x,'country',x)).join(''))+row('年份',chip('全部','year','')+META.years.map(x=>chip(x.endsWith('s')?x.slice(0,-1)+'年代':x,'year',x)).join(''))}else{html+=row('风格',chip('全部','genre','')+tmdbGenres.map(x=>chip(x.name,'genre',x.id)).join(''))}$('#filters').innerHTML=html;document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>change(b.dataset.key,b.dataset.value))}
async function change(key,value){S[key]=value;S.page=1;S.has_more=false;if(key==='media_type')await metadata();sync();load(false)}function sync(){const q=new URLSearchParams();['provider','media_type','sort','genre','country','year'].forEach(k=>{if(S[k])q.set(k,S[k])});history.replaceState(null,'','/explore?'+q);drawFilters()}function restore(){const q=new URLSearchParams(location.search);['provider','media_type','sort','genre','country','year'].forEach(k=>{if(q.has(k))S[k]=q.get(k)})}
async function providers(){const d=await fetch('/api/explore/providers').then(r=>r.json());$('#providers').innerHTML=d.items.map(p=>`<button class="provider ${p.id===S.provider?'active':''} ${p.configured?'':'unconfigured'}" data-provider="${p.id}"><span class="picon">${providerIcon(p.icon)}</span><span>${esc(p.name)}</span></button>`).join('');document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=async()=>{S.provider=b.dataset.provider;S.page=1;S.genre='';S.year='';S.country='';S.sort=S.provider==='douban'?'recommend':'popularity.desc';await providers();await metadata();sync();load(false)})}
async function metadata(){const d=await fetch('/api/explore/filters?media_type='+S.media_type).then(r=>r.json());META=d.douban||META;tmdbGenres=d.data?.genres||[];drawFilters()}
''' + PROVIDER_ICONS_JS + MEDIA_CARD_JS + '''
function skeleton(){$('#content').innerHTML=`<div class="grid">${'<div class="skeleton"></div>'.repeat(12)}</div>`}function empty(){return `<div class="state"><h2>当前筛选条件暂无结果</h2><p>可以清除部分条件或重置筛选。</p><button onclick="clearOne()">清除一个条件</button><button onclick="resetAll()">重置筛选</button></div>`}function clearOne(){for(const k of ['year','country','genre'])if(S[k]){S[k]='';S.page=1;sync();load(false);return}}function resetAll(){Object.assign(S,{media_type:'movie',sort:S.provider==='douban'?'recommend':'popularity.desc',genre:'',country:'',year:'',page:1});sync();load(false)}
async function load(append){if(controller)controller.abort();controller=new AbortController();const id=++S.request;S.loading=true;if(!append)skeleton();$('#summary').textContent='正在加载影视数据…';const q=new URLSearchParams({provider:S.provider,media_type:S.media_type,sort:S.sort,genre:S.genre,country:S.country,year:S.year,page:S.page});try{const r=await fetch('/api/explore/discover?'+q,{signal:controller.signal});const d=await r.json();if(id!==S.request)return;if(!r.ok)throw Error(d.detail||'接口请求失败');if(d.error&&!d.items?.length){$('#content').innerHTML=`<div class="state"><h2>加载失败</h2><p>${esc(d.error)}</p><button onclick="load(false)">重试</button></div>`;S.has_more=false}else if(!d.items?.length){$('#content').innerHTML=empty();S.has_more=false}else{const html=d.items.map(cardHTML).join('');if(append&&$('#content .grid'))$('#content .grid').insertAdjacentHTML('beforeend',html);else $('#content').innerHTML='<div class="grid">'+html+'</div>';bindCards();loadSubState();S.has_more=!!d.has_more;$('#summary').textContent=`第 ${d.page} 页 · ${d.total||d.items.length} 条${S.provider==='douban'?'豆瓣':''}结果${d.cached?' · 缓存':''}`}$('#sentinel').classList.toggle('hidden',!S.has_more)}catch(e){if(e.name!=='AbortError'&&id===S.request)$('#content').innerHTML=`<div class="state"><h2>网络请求失败</h2><p>${esc(e.message)}</p><button onclick="load(false)">重试</button></div>`}finally{if(id===S.request)S.loading=false}}
new IntersectionObserver(es=>{if(es[0].isIntersecting&&S.has_more&&!S.loading){S.page++;load(true)}}).observe($('#sentinel'));$('#reset').onclick=resetAll;restore();providers();metadata().then(()=>{sync();load(false)});
</script></body></html>'''
