"""MovieArk unified media search page."""

from .theme import theme_head
from .ui_common import sidebar_html, MEDIA_CARD_CSS, MEDIA_CARD_JS


def search_html() -> str:
    return r'''<!doctype html><html lang="zh-CN"><head>''' + theme_head() + r'''<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>搜索 · 影舟 MovieArk</title><style>
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 78% 5%,var(--accent-soft),var(--bg-deep) 42%);color:var(--text);font:14px system-ui,"Microsoft YaHei"}.shell{display:grid;grid-template-columns:240px minmax(0,1fr);min-height:100vh}.side{padding:20px 14px;background:var(--sidebar-bg);border-right:1px solid var(--line)}.logo{font-size:23px;font-weight:800;color:var(--accent-primary);padding:5px 8px 27px}.group{font-size:12px;color:var(--text-muted);border-bottom:1px solid var(--border-secondary);padding:18px 8px 8px}.nav{display:block;color:var(--text-secondary);text-decoration:none;padding:13px 12px;margin:6px 0;border-radius:11px;font-weight:700}.nav:hover,.nav.active{color:var(--accent-primary);background:var(--hover-bg)}.main{padding:42px;max-width:1450px;width:100%;margin:auto;align-self:start}.head h1{font-size:30px;color:var(--text-primary);margin:0 0 8px}.head p{color:var(--muted)}.searchbox{display:flex;gap:10px;padding:16px;border:1px solid var(--line);background:var(--panel);border-radius:15px;margin:25px 0}.searchbox input{flex:1;background:var(--input-bg);border:1px solid var(--input-border);color:var(--text-primary);border-radius:10px;padding:14px;font-size:16px}.searchbox select,.searchbox button{border:1px solid var(--accent-secondary);background:var(--accent-soft);color:var(--accent-primary);border-radius:10px;padding:0 18px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(145px,1fr));gap:14px}''' + MEDIA_CARD_CSS + '''.state{text-align:center;padding:70px 20px;border:1px solid var(--state-line);background:var(--panel);border-radius:14px;color:var(--muted)}.state button{margin:6px;padding:9px 14px;border:1px solid var(--accent-primary);background:var(--button-secondary-bg);color:var(--accent-primary);border-radius:8px;cursor:pointer}.hist{display:flex;align-items:center;gap:10px;padding:11px 14px;border:1px solid var(--line);background:var(--panel);border-radius:12px;margin:8px 0;cursor:pointer}.hist:hover{border-color:var(--cyan)}.hist .h-title{font-weight:700;color:var(--text-primary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:320px}.hist .h-sub{font-size:12px;color:var(--muted);margin-top:3px}.hist button{margin-left:auto;border:1px solid var(--accent-primary);background:var(--button-secondary-bg);color:var(--accent-primary);border-radius:8px;padding:6px 12px;cursor:pointer}.histhead{display:flex;align-items:center;gap:12px;margin:26px 0 6px}.histhead h2{font-size:17px;color:var(--text-primary);margin:0}.histhead button{border:0;background:none;color:var(--danger);cursor:pointer;font-size:12px}@media(max-width:800px){.shell{display:block}.side{display:none}.main{padding:20px}.searchbox{flex-wrap:wrap}.searchbox input{flex-basis:100%}}@media(max-width:430px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style></head><body><div class="shell">''' + sidebar_html("search") + '''<main class="main"><div class="head"><h1>影视与资源搜索</h1><p>输入片名，先匹配影视资料，再进入同一个详情与影巢资源搜索流程。</p></div><form class="searchbox" id="form"><input id="keyword" placeholder="输入电影或电视剧名称" autocomplete="off"><select id="type"><option value="">全部类型</option><option value="movie">电影</option><option value="tv">电视剧</option></select><button>搜索</button></form><section id="history"></section><section id="result"><div class="state">输入影视名称开始搜索</div></section></main></div><script>
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));''' + MEDIA_CARD_JS + '''
async function loadHistory(){try{const d=await fetch('/api/web/search-history').then(r=>r.json());const items=d.items||[];if(!items.length){$('#history').innerHTML='';return}$('#history').innerHTML='<div class="histhead"><h2>⌕ 最近搜索</h2><button id="clearHist">清空记录</button></div>'+items.map(h=>`<div class="hist" data-id="${h.id}" data-j="${encodeURIComponent(JSON.stringify(h))}"><div><div class="h-title">${esc(h.title)}</div><div class="h-sub">${h.media_type==='tv'?'电视剧':'电影'}${h.year?' · '+esc(h.year):''} · ${h.result_count??0} 条结果 · ${new Date(Number(h.searched_at)*1000).toLocaleString('zh-CN',{hour12:false})}</div></div><button data-del="${h.id}">删除</button></div>`).join('');document.querySelectorAll('.hist').forEach(el=>el.onclick=e=>{if(e.target.dataset.del)return delHistory(+e.target.dataset.del);const h=JSON.parse(decodeURIComponent(el.dataset.j));location.href='/resources?'+new URLSearchParams({media_type:h.media_type||'movie',tmdb_id:h.tmdb_id||0,douban_id:h.douban_id||'',title:h.title,poster:h.poster||''})});$('#clearHist').onclick=clearHistory}catch(e){}}async function delHistory(id){const r=await fetch('/api/web/search-history/'+id,{method:'DELETE'});loadHistory()}async function clearHistory(){if(!confirm('确认清空最近搜索记录吗？'))return;await fetch('/api/web/search-history',{method:'DELETE'});loadHistory()}$('#form').onsubmit=async e=>{e.preventDefault();const k=$('#keyword').value.trim();if(!k)return;$('#result').innerHTML='<div class="state">正在匹配影视资料…</div>';try{const r=await fetch('/api/web/media/search?'+new URLSearchParams({keyword:k,media_type:$('#type').value})),d=await r.json();if(!r.ok)throw Error(apiMsg(d, '搜索失败'));if(!d.items.length){$('#result').innerHTML='<div class="state">未匹配到影视资料，请尝试完整片名。</div>';return}$('#result').innerHTML='<div class="grid">'+d.items.map(cardHTML).join('')+'</div>';bindCards();loadSubState()}catch(err){$('#result').innerHTML=`<div class="state">搜索失败：${esc(err.message)}<br><button onclick="$('#form').requestSubmit()">重试</button></div>`}};loadHistory();
</script></body></html>
'''
