"""MovieArk unified media search page."""


def search_html() -> str:
    return r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>搜索 · 影舟 MovieArk</title><style>
:root{--gold:#d6b66f;--cyan:#20c4dc;--line:#174c54;--text:#eadfca;--muted:#9d927e}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 78% 5%,#332313,#080705 42%);color:var(--text);font:14px system-ui,"Microsoft YaHei"}.shell{display:grid;grid-template-columns:240px minmax(0,1fr);min-height:100vh}.side{padding:20px 14px;background:#080704f5;border-right:1px solid var(--line)}.logo{font-size:23px;font-weight:800;color:var(--gold);padding:5px 8px 27px}.group{font-size:12px;color:#746b5c;border-bottom:1px solid #46351a;padding:18px 8px 8px}.nav{display:block;color:#b8aa8f;text-decoration:none;padding:13px 12px;margin:6px 0;border-radius:11px;font-weight:700}.nav:hover,.nav.active{color:#49d8ed;background:#103b41}.main{padding:42px;max-width:1450px;width:100%;margin:auto;align-self:start}.head h1{font-size:30px;color:var(--gold);margin:0 0 8px}.head p{color:var(--muted)}.searchbox{display:flex;gap:10px;padding:16px;border:1px solid var(--line);background:#12100b;border-radius:15px;margin:25px 0}.searchbox input{flex:1;background:#070604;border:1px solid #285f67;color:#eee;border-radius:10px;padding:14px;font-size:16px}.searchbox select,.searchbox button{border:1px solid #28727d;background:#113940;color:#55d9eb;border-radius:10px;padding:0 18px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(145px,1fr));gap:14px}.card{background:#11100c;border:1px solid #25454a;border-radius:12px;overflow:hidden;cursor:pointer}.card:hover{border-color:var(--cyan);transform:translateY(-2px)}.card img{width:100%;aspect-ratio:2/3;object-fit:cover;background:#211d15}.meta{padding:10px}.title{font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sub{font-size:12px;color:var(--muted);margin-top:5px}.state{text-align:center;padding:70px 20px;border:1px solid #49361c;background:#12100b;border-radius:14px;color:var(--muted)}@media(max-width:800px){.shell{display:block}.side{display:none}.main{padding:20px}.searchbox{flex-wrap:wrap}.searchbox input{flex-basis:100%}}
</style></head><body><div class="shell"><aside class="side"><div class="logo">◉ 影舟 MovieArk</div><div class="group">发现</div><a class="nav" href="/rankings">🏆 榜单</a><a class="nav" href="/explore">◉ 汇影</a><a class="nav active" href="/search">⌕ 搜索</a><div class="group">订阅</div><a class="nav" href="/subscriptions">☷ 订阅列表</a><a class="nav" href="/tasks">▣ 订阅任务</a><a class="nav" href="/unlocks">◴ 解锁记录</a><div class="group">系统</div><a class="nav" href="/authorizations">⌘ 授权中心</a><a class="nav" href="/settings">⚙ 业务设置</a><a class="nav" href="/telegram">✈ Telegram</a></aside><main class="main"><div class="head"><h1>影视与资源搜索</h1><p>输入片名，先匹配影视资料，再进入同一个详情与影巢资源搜索流程。</p></div><form class="searchbox" id="form"><input id="keyword" placeholder="输入电影或电视剧名称" autocomplete="off"><select id="type"><option value="">全部类型</option><option value="movie">电影</option><option value="tv">电视剧</option></select><button>搜索</button></form><section id="result"><div class="state">输入影视名称开始搜索</div></section></main></div><script>
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function ph(){return "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='260' height='390'%3E%3Crect width='100%25' height='100%25' fill='%23211d15'/%3E%3C/svg%3E"}function open(x){location.href='/resources?'+new URLSearchParams({media_type:x.media_type,tmdb_id:x.tmdb_id||0,douban_id:x.douban_id||'',title:x.title||'',year:x.year||'',poster:x.poster||'',backdrop:x.backdrop||'',rating:x.rating||'',overview:x.overview||''})}$('#form').onsubmit=async e=>{e.preventDefault();const k=$('#keyword').value.trim();if(!k)return;$('#result').innerHTML='<div class="state">正在匹配影视资料…</div>';try{const r=await fetch('/api/web/media/search?'+new URLSearchParams({keyword:k,media_type:$('#type').value})),d=await r.json();if(!r.ok)throw Error(d.detail||'搜索失败');if(!d.items.length){$('#result').innerHTML='<div class="state">未匹配到影视资料，请尝试完整片名。</div>';return}$('#result').innerHTML='<div class="grid">'+d.items.map((x,i)=>`<article class="card" data-i="${i}"><img loading="lazy" src="${esc(x.poster||ph())}"><div class="meta"><div class="title">${esc(x.title)}</div><div class="sub">${esc(x.year||'年份未知')} · ${x.media_type==='tv'?'电视剧':'电影'}</div></div></article>`).join('')+'</div>';document.querySelectorAll('.card').forEach(c=>c.onclick=()=>open(d.items[+c.dataset.i]))}catch(err){$('#result').innerHTML=`<div class="state">搜索失败：${esc(err.message)}<br><button onclick="$('#form').requestSubmit()">重试</button></div>`}};
</script></body></html>'''
